backend:
  name: git-gateway
  branch: main

# publish_mode: editorial_workflow
media_folder: "assets/images/posts" # Media files will be stored in the repo under src/assets/images/posts
public_folder: "/assets/images/posts" # The src attribute for uploaded media will begin with assets/images/posts

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/blogs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Title" }
      - { label: "Image", name: "image", widget: "image" }
      - { name: "description", label: "Description" }
      - { name: "autor", label: "Autor" }
      - { name: "correo", label: "Correo" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "content", label: "Content", widget: "markdown" }
      - {
          name: "highlight",
          label: "Highlight",
          widget: "boolean",
          default: false,
          hint: "Display posts in home's highlights",
        }

show_preview_links: true
